In [5]:
import sys
!{sys.executable} -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu


Looking in indexes: https://download.pytorch.org/whl/cpu
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
   ---------------------------------------- 0.0/113.6 MB ? eta -:--:--
   ---------------------------------------- 0.8/113.6 MB 5.6 MB/s eta 0:00:21
    --------------------------------------- 1.8/113.6 MB 5.0 MB/s eta 0:00:23
    --------------------------------------- 2.1/113.6 MB 5.1 MB/s eta 0:00:22
    --------------------------------------- 2.4/113.6 MB 3.1 MB/s eta 0:00:36
    --------------------------------------- 2.6/113.6 MB 2.6 MB/s eta 0:00:43
   - -------------------------------------- 3.4/113.6 MB 2.8 MB/s eta 0:00:40
   - -------------------------------------- 3.7/113.6 MB 2.7 MB/s eta 0:00:42
   - -------------------------------------- 3.9/113.6 MB 2.6 MB/s eta 0:00:43
   - -------------------------------------- 4.5/113.6 MB 2

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [6]:
import torch
print(torch.__version__)

2.10.0+cpu


In [7]:
torch.__version__

'2.10.0+cpu'

In [10]:
# scalar 
scalar = torch.tensor(6)
scalar.item() 

6

In [9]:
# how to create a vector of tensors ?
vector = torch.tensor([7,7])
vector , vector.ndim 

(tensor([7, 7]), 1)

In [11]:
# how to identify the shape of the tensor ?
vector.shape , scalar.shape

(torch.Size([2]), torch.Size([]))

In [12]:
# matrix 
matrix = torch.tensor([[4,7],[5,6]])
matrix , matrix.ndim

(tensor([[4, 7],
         [5, 6]]),
 2)

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
d3_tensor = torch.tensor([[ [1,2,3],
                        [4,5,6],
                        [7,8,9]
                        ]])
d3_tensor , d3_tensor.ndim , d3_tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 3,
 torch.Size([1, 3, 3]))

In [15]:
# creating a random tensor

random_tensor = torch.rand(size=(4,3))
random_tensor

tensor([[0.7898, 0.6389, 0.6554],
        [0.8651, 0.6149, 0.4871],
        [0.8592, 0.4784, 0.5617],
        [0.8497, 0.9629, 0.5329]])

In [16]:
# check the shape
random_tensor.shape , random_tensor.ndim

(torch.Size([4, 3]), 2)

5 min read : https://pytorch.org/docs/stable/tensors.html

In [17]:
random_tensor.dtype

torch.float32

RGB images = [red , green , blue]

In [18]:
x_tensor = torch.rand(size=(224,224,3))
x_tensor.ndim 

3

In [19]:
# zeros 
zero_tensor = torch.zeros(size=(2,2,8))
zero_tensor , zero_tensor.shape , zero_tensor.ndim , zero_tensor.dtype

(tensor([[[0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.]]]),
 torch.Size([2, 2, 8]),
 3,
 torch.float32)

In [20]:
# ones 
ones_tensor = torch.ones(size=(2,2,8))
ones_tensor , ones_tensor.shape , ones_tensor.ndim , ones_tensor.dtype

(tensor([[[1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1.]]]),
 torch.Size([2, 2, 8]),
 3,
 torch.float32)

In [21]:
# arange
t_tensor = torch.arange(0,10,1)
t_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
r_tensor = torch.tensor(data=[4,5,7],
                        dtype=torch.float64,
                        device='cpu',
                        requires_grad=False
                        )
r_tensor , r_tensor.dtype , r_tensor.device

# tensor operations
1. multiply
2. addition
3. subtraction
4. division

In [22]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [23]:
x = x + 10
x

tensor([11, 12, 13])

In [24]:
x = x - 2
x 

tensor([ 9, 10, 11])

In [25]:
x = x * 2
x

tensor([18, 20, 22])

In [26]:
x = x / 2
x

tensor([ 9., 10., 11.])

In [27]:
y = x * x
y

tensor([ 81., 100., 121.])

In [28]:
x = torch.multiply(x, 10)
x

tensor([ 90., 100., 110.])

In [29]:
x = torch.matmul(x ,x)
x

tensor(30200.)

In [30]:
x.shape , x.ndim

(torch.Size([]), 0)

In [31]:
tensor_a = torch.rand(size=(2,3))
tensor_a , tensor_a.shape

(tensor([[0.7123, 0.7942, 0.2777],
         [0.2466, 0.9300, 0.6777]]),
 torch.Size([2, 3]))

In [32]:
tensor_b = torch.rand(size=(3,8))
tensor_b , tensor_b.shape

(tensor([[0.1156, 0.7811, 0.8959, 0.4393, 0.5943, 0.9063, 0.0881, 0.4349],
         [0.8788, 0.7765, 0.0397, 0.2576, 0.4779, 0.9974, 0.8792, 0.7185],
         [0.3832, 0.2311, 0.3477, 0.3915, 0.3932, 0.4537, 0.7092, 0.7374]]),
 torch.Size([3, 8]))

In [33]:
tensor_f = torch.matmul(tensor_a,tensor_b)
tensor_f

tensor([[0.8868, 1.2372, 0.7662, 0.6262, 0.9121, 1.5637, 0.9580, 1.0852],
        [1.1055, 1.0713, 0.4934, 0.6131, 0.8574, 1.4585, 1.3199, 1.2751]])

In [36]:
# manual seed generation
torch.manual_seed(42)

random_tensor = torch.rand((2,3))
random_tensor

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [37]:
from torch import nn

In [38]:
linear_layer = nn.Linear(in_features=6,out_features=4)

tensor_L = torch.rand(size=(4,6))

x = linear_layer(tensor_L)
x

tensor([[ 0.6558,  0.0566,  0.1838, -0.5983],
        [ 0.6037,  0.2153, -0.0014, -0.6023],
        [ 0.5914,  0.0809,  0.1573, -0.5555],
        [ 0.8549,  0.0615,  0.2566, -0.5615]], grad_fn=<AddmmBackward0>)

In [39]:
v = torch.arange(0,16,2)
v

tensor([ 0,  2,  4,  6,  8, 10, 12, 14])

In [40]:
v.min()

tensor(0)

In [41]:
v.max()

tensor(14)

In [42]:
max_index = v.argmax()
max_index

tensor(7)

In [44]:
min_index = v.argmin()
min_index

tensor(0)

In [45]:
float_tensor = torch.arange(0.,10,1.)
float_tensor , float_tensor.dtype

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [46]:
float_tensor = torch.arange(0,10,1)
float_tensor , float_tensor.dtype

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

In [47]:
# transpose
random_tensor , random_tensor.shape

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]]),
 torch.Size([2, 3]))

In [48]:
random_tensor_transpose = torch.transpose(random_tensor,dim0=0,dim1=1)
random_tensor_transpose , random_tensor_transpose.shape 

(tensor([[0.8823, 0.9593],
         [0.9150, 0.3904],
         [0.3829, 0.6009]]),
 torch.Size([3, 2]))

In [49]:
random_tensor_transpose_v2 = random_tensor.t()
random_tensor_transpose_v2 , random_tensor_transpose_v2.shape 

(tensor([[0.8823, 0.9593],
         [0.9150, 0.3904],
         [0.3829, 0.6009]]),
 torch.Size([3, 2]))

In [50]:
# mean of some tensor
mean_tensor = torch.arange(0,10,1)
mean_tensor , mean_tensor.dtype

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

In [51]:
mean_tensor_f32 = mean_tensor.type(torch.float32)
mean_tensor_f32 , mean_tensor_f32.dtype

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [52]:
mean_tensor_r = mean_tensor_f32.mean()
mean_tensor_r

tensor(4.5000)

In [53]:
# how to reshape a tensor

mean_tensor_f32 , mean_tensor_f32.shape , mean_tensor_f32.dtype , mean_tensor_f32.ndim

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([10]),
 torch.float32,
 1)

In [54]:
reshaped_tensor = mean_tensor_f32.reshape(1,1,-1)
reshaped_tensor , reshaped_tensor.shape , reshaped_tensor.ndim

(tensor([[[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]]),
 torch.Size([1, 1, 10]),
 3)

In [55]:
reshaped_tensor_v2 = mean_tensor_f32.reshape(1,10)
reshaped_tensor_v2

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [56]:
x_stacked = torch.stack([x,x,x])
x_stacked

tensor([[[ 0.6558,  0.0566,  0.1838, -0.5983],
         [ 0.6037,  0.2153, -0.0014, -0.6023],
         [ 0.5914,  0.0809,  0.1573, -0.5555],
         [ 0.8549,  0.0615,  0.2566, -0.5615]],

        [[ 0.6558,  0.0566,  0.1838, -0.5983],
         [ 0.6037,  0.2153, -0.0014, -0.6023],
         [ 0.5914,  0.0809,  0.1573, -0.5555],
         [ 0.8549,  0.0615,  0.2566, -0.5615]],

        [[ 0.6558,  0.0566,  0.1838, -0.5983],
         [ 0.6037,  0.2153, -0.0014, -0.6023],
         [ 0.5914,  0.0809,  0.1573, -0.5555],
         [ 0.8549,  0.0615,  0.2566, -0.5615]]], grad_fn=<StackBackward0>)

In [57]:
k = torch.arange(0,10,1)
k , k.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [58]:
k_mod = k.reshape(1,-1)
k_mod , k_mod.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [59]:
k_mod_v2 = k_mod.squeeze()
k_mod_v2 , k_mod_v2.shape 

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [60]:
k_mod_v3 = k_mod_v2.unsqueeze(dim=1) # (10,1) (1,10)
k_mod_v3 , k_mod_v3.shape 

(tensor([[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([10, 1]))

In [61]:
# permute     (10,20,1)    ->  (1,20,10)

i = torch.rand(224,228,3)
i.shape

torch.Size([224, 228, 3])

In [62]:
i_permute = torch.permute(i,(2,0,1))
i_permute.shape

torch.Size([3, 224, 228])

In [63]:
x = torch.rand(2,2,3)
x

tensor([[[0.7240, 0.6005, 0.7844],
         [0.6948, 0.2316, 0.5119]],

        [[0.3579, 0.7580, 0.3559],
         [0.4799, 0.7994, 0.9928]]])

In [64]:
x[1][1][2]

tensor(0.9928)

In [65]:
import numpy as np

In [66]:
r = np.arange(1.0,7.0)
r , type(r)

(array([1., 2., 3., 4., 5., 6.]), numpy.ndarray)

In [67]:
r_tensor = torch.from_numpy(r)
type(r_tensor)

torch.Tensor

In [68]:
x = torch.arange(0,10,1)
x , type(x)

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Tensor)

In [69]:
x_numpy = x.numpy()
type(x_numpy)

numpy.ndarray

In [70]:
# set the manual seed

torch.manual_seed(42)

random_tensor = torch.rand(2,2)
random_tensor

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])

In [71]:
# Gpu

!nvidia-smi

Wed Feb 18 14:35:38 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 573.44                 Driver Version: 573.44         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA T600 Laptop GPU       WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   60C    P0            N/A  / 5001W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [72]:
# device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [73]:
# check for other GPU's
torch.cuda.device_count()

0

In [74]:
tensor = torch.tensor([2,5])
tensor , tensor.device

(tensor([2, 5]), device(type='cpu'))

In [75]:
tensor_gpu = tensor.to('cuda')

AssertionError: Torch not compiled with CUDA enabled

In [76]:
tensor_gpu.device

NameError: name 'tensor_gpu' is not defined

In [77]:
# device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [78]:
gpu_tensor = tensor.to(device)
gpu_tensor.device

device(type='cpu')

In [79]:
cpu_tensor = gpu_tensor.cpu()
cpu_tensor.device , type(cpu_tensor)

(device(type='cpu'), torch.Tensor)

In [80]:
cpu_numpy_tensor = gpu_tensor.cpu().numpy()
type(cpu_numpy_tensor)

numpy.ndarray

In [81]:
import torch
import torch.nn as nn

class MLP(nn.Module):
    def __init__(self, input_dim, N1, output_dim):
        super().__init__()   # ⚠️ OBLIGATOIRE

        self.fc1 = nn.Linear(input_dim, N1)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(N1, output_dim)

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.fc2(x)
        return x

model = MLP(10,5,1)
print(model)


MLP(
  (fc1): Linear(in_features=10, out_features=5, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=5, out_features=1, bias=True)
)
